# Generated by Django 4.2.24 on 2026-07-06 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_policycomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypeUsageRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('max_consecutive_days', models.PositiveIntegerField(help_text='The maximum number of consecutive leave days the employee can take.', verbose_name='Maximum Consecutive Days')),
                ('valid_until', models.DateField(help_text='The restriction applies to leave days up to and including this date.', verbose_name='Valid Until')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_usage_restrictions', to='employee.employee', verbose_name='Employee')),
                ('leave_type_ids', models.ManyToManyField(help_text='Leaves of all the selected leave types are counted together when checking the consecutive days limit.', related_name='usage_restrictions', to='leave.leavetype', verbose_name='Leave Types')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Leave Usage Restriction',
                'verbose_name_plural': 'Leave Usage Restrictions',
                'ordering': ['-id'],
            },
        ),
    ]
