# Generated by Django 4.2.24 on 2026-06-20 12:10

from django.db import migrations


class Migration(migrations.Migration):
    # This migration originally added the custom employee/bank fields, but
    # 0001_initial was later regenerated and already contains all of them,
    # so applying both on a fresh database failed with "duplicate column".
    # The file is kept as a no-op so databases that already recorded it as
    # applied keep a consistent migration history.

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = []
