# Generated by Django 4.2.24 on 2026-06-20 20:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    # EmployeeLeaveApprover was originally created here, but 0001_initial was
    # later regenerated and already contains the model, so applying both on a
    # fresh database failed with "table already exists". The file is kept as
    # a no-op so databases that already recorded it as applied keep a
    # consistent migration history.

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0002_employee_children_info_employee_np_branch_and_more"),
    ]

    operations = []
