# Generated by Django 4.2.24 on 2026-07-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_policycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgedocument',
            options={'ordering': ['id'], 'verbose_name': 'Knowledge Document', 'verbose_name_plural': 'Knowledge Documents'},
        ),
    ]
