# Generated by Django 4.2.24 on 2026-04-13 11:57

from django.db import migrations


class Migration(migrations.Migration):
    # Reimbursement.sub_type was originally added here, but 0001_initial was
    # later regenerated and already contains the field, so applying both on a
    # fresh database failed with "duplicate column". The file is kept as a
    # no-op so databases that already recorded it as applied keep a
    # consistent migration history.

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = []
